### PR TITLE
upgrade: 4.0.0 release

### PR DESCRIPTION
**Pull request by sjaanus**

### CODE REVIEW

**Review by FredrikOseberg — APPROVED** [review]

**Comment by jameshartig** [comment]
I think the `go.mod` needs to change have `github.com/Unleash/unleash-client-go/v4` and does the branch need to change too? This was merged into `v3`.

**Comment by FredrikOseberg** [comment]
> I think the `go.mod` needs to change have `github.com/Unleash/unleash-client-go/v4` and does the branch need to change too? This was merged into `v3`.

You're right. I'll raise this internally and we'll get a fix out promptly. Thanks!

**Comment by FredrikOseberg** [comment]
> I think the `go.mod` needs to change have `github.com/Unleash/unleash-client-go/v4` and does the branch need to change too? This was merged into `v3`.

@jameshartig I think we've solved this now, can you confirm when it suits you? 

Best, Fredrik

**Comment by jameshartig** [comment]
@FredrikOseberg yep! I was able to pull in v4 now and everything seems to be working. Thanks for the quick fix!!

**Comment by FredrikOseberg** [comment]
> @FredrikOseberg yep! I was able to pull in v4 now and everything seems to be working. Thanks for the quick fix!!

Amazing! Have a good weekend :)

**Pull request merged**
