### PR TITLE
Expose defaultStorage

### PR DESCRIPTION
**Pull request by kskumgk63**
I would like to embed defaultStorage to my original struct because storage customization would be easy.

Related slack link: https://unleash-community.slack.com/archives/CGN5JT69F/p1622789881074700

### CODE REVIEW

**Review by chriswk — APPROVED** [review]
You could potentially break the client with too much modification. However, I think this seems like a reasonable change

**Comment by chriswk** [comment]
Hi @jrbarron - Talked to @FredrikOseberg  on this and we couldn't think of a major argument for not exposing this, but I'd love to have your opinion on this as well before merging.

**Comment by jrbarron** [comment]
Seems reasonable to me :) It was most likely private to reduce the API surface area of the package and since it was the first implementation of the storage engine we did not know how long it would survive at that point.

**Review by jrbarron — APPROVED** [review]

**Comment by kskumgk63** [comment]
@chriswk @jrbarron 
Thanks for approves, Could you merge this PR?

**Pull request merged**
